image: 
  file: Dockerfile

ports:
  - port: 8080 #NodeRed
    onOpen: ignore #open-preview
  - port: 8050  #VitalsFaker
  - port: 8090 #JSONserver
tasks:
 # - before: npm install -g --unsafe-perm node-red && npm install --prefix ./VitalsFaker json-server faker fs
 # - command: gp await-port 8080
 # - before: npm install -g --unsafe-perm node-red
 - name: StartUp 
   init: npm install 
   command: node VitalsFaker/faker1

 - name: JSONserver setup
   init: npm install --prefix ./VitalsFaker json-server #-g json-server 
   command: node VitalsFaker/jsonserver

 - name: Good to Go   
   command: node VitalsFaker/test1  & node-red -p 8080 -u ./NRed lib/flows/flowsNR.json